"""
Custom operators for Presidio Anonymizer that use synthetic data generation.
"""

from typing import Dict, Any, Optional
from presidio_anonymizer.entities import OperatorConfig
from presidio_anonymizer.operators import Operator

from .morph_generator import MorphologicalGenerator


class SyntheticReplaceOperator(Operator):
    """
    Operator that replaces PII with synthetic data generated by MorphologicalGenerator.
    """
    
    def __init__(self):
        """Initialize the synthetic replace operator."""
        super().__init__()
        self.generator = None  # Will be initialized on first use
    
    def _get_generator(self) -> MorphologicalGenerator:
        """Lazy initialization of the generator."""
        if self.generator is None:
            self.generator = MorphologicalGenerator()
        return self.generator
    
    def operate(
        self,
        text: str,
        params: Optional[Dict[str, Any]] = None
    ) -> Dict[str, str]:
        """
        Replace text with synthetic data.
        
        Args:
            text: Text to anonymize
            params: Parameters including 'entity_type' and optionally 'locale', 'spacy_model'
            
        Returns:
            Dictionary with 'text' key containing the anonymized text
        """
        if params is None:
            params = {}
        
        entity_type = params.get("entity_type", "PERSON")
        
        # Map Presidio entity types to our internal format
        entity_mapping = {
            "PERSON": "{name}",
            "LOCATION": "{city}",
            "PHONE_NUMBER": "{phone}",
            "EMAIL_ADDRESS": "{email}",
            "CREDIT_CARD": "{bank-account}",
        }
        
        # Use custom entity type if provided, otherwise map from Presidio
        custom_entity_type = params.get("custom_entity_type")
        if custom_entity_type:
            entity_type_key = custom_entity_type
        else:
            entity_type_key = entity_mapping.get(entity_type, "{name}")
        
        generator = self._get_generator()
        synthetic_text = generator.generate(text, entity_type_key)
        
        return {"text": synthetic_text}
    
    def validate(self, params: Optional[Dict[str, Any]] = None) -> None:
        """
        Validate operator parameters.
        
        Args:
            params: Parameters to validate
        """
        # Basic validation - can be extended
        if params and "entity_type" not in params and "custom_entity_type" not in params:
            raise ValueError("Either 'entity_type' or 'custom_entity_type' must be provided")


class SyntheticFakerOperator(Operator):
    """
    Operator that uses Faker directly for simple synthetic replacements.
    Useful when morphological awareness is not needed.
    """
    
    def __init__(self):
        """Initialize the Faker operator."""
        super().__init__()
        self.generator = None
    
    def _get_generator(self) -> MorphologicalGenerator:
        """Lazy initialization of the generator."""
        if self.generator is None:
            self.generator = MorphologicalGenerator()
        return self.generator
    
    def operate(
        self,
        text: str,
        params: Optional[Dict[str, Any]] = None
    ) -> Dict[str, str]:
        """
        Replace text with Faker-generated synthetic data.
        
        Args:
            text: Text to anonymize
            params: Parameters including 'entity_type'
            
        Returns:
            Dictionary with 'text' key containing the anonymized text
        """
        if params is None:
            params = {}
        
        entity_type = params.get("entity_type", "PERSON")
        generator = self._get_generator()
        
        # Direct Faker access for simple cases
        faker = generator.faker
        
        faker_methods = {
            "PERSON": lambda: f"{faker.first_name()} {faker.last_name()}",
            "LOCATION": faker.city,
            "PHONE_NUMBER": faker.phone_number,
            "EMAIL_ADDRESS": faker.email,
            "ADDRESS": faker.address,
        }
        
        method = faker_methods.get(entity_type)
        if method:
            synthetic_text = method() if callable(method) else method
        else:
            synthetic_text = generator.generate(text, entity_type)
        
        return {"text": synthetic_text}
    
    def validate(self, params: Optional[Dict[str, Any]] = None) -> None:
        """
        Validate operator parameters.
        
        Args:
            params: Parameters to validate
        """
        pass  # No specific validation needed


# Factory function to create operator configs
def create_synthetic_operator_config(
    entity_type: str,
    custom_entity_type: Optional[str] = None,
    operator_type: str = "synthetic_replace"
) -> OperatorConfig:
    """
    Create an OperatorConfig for synthetic replacement.
    
    Args:
        entity_type: Presidio entity type
        custom_entity_type: Custom entity type (e.g., "{name}", "{city}")
        operator_type: Type of operator ("synthetic_replace" or "synthetic_faker")
        
    Returns:
        OperatorConfig instance
    """
    params = {}
    if custom_entity_type:
        params["custom_entity_type"] = custom_entity_type
    else:
        params["entity_type"] = entity_type
    
    if operator_type == "synthetic_replace":
        operator = SyntheticReplaceOperator()
    else:
        operator = SyntheticFakerOperator()
    
    return OperatorConfig(
        operator_name=operator_type,
        params=params
    )

